version: '3.7'

services:

  front_end:
    environment:
      SECRET_KEY: ${SECRET_KEY}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      URL_SERVICIOS: ${URL_SERVICIOS}
      CLIENTE_SERVICIOS_USR: ${CLIENTE_SERVICIOS_USR}
      CLIENTE_SERVICIOS_PWD: ${CLIENTE_SERVICIOS_PWD}
    build: ./contenedor_front_end
    restart: always
    container_name: eminus_crawler_front_end
    volumes:
      - ./contenedor_front_end/front_end:/code
    depends_on:
      - bd_front_end
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "250M"

  back_end:
    environment:
      SERVICIOS_SECRET_KEY: ${SERVICIOS_SECRET_KEY}
      DB_SERVICIOS_NAME: ${DB_SERVICIOS_NAME}
      DB_SERVICIOS_USER: ${DB_SERVICIOS_USER}
      DB_SERVICIOS_PASSWORD: ${DB_SERVICIOS_PASSWORD}
      DB_SERVICIOS_HOST: ${DB_SERVICIOS_HOST}
      DB_SERVICIOS_PORT: ${DB_SERVICIOS_PORT}
      CLIENTE_SERVICIOS_USR: ${CLIENTE_SERVICIOS_USR}
      CLIENTE_SERVICIOS_PWD: ${CLIENTE_SERVICIOS_PWD}
    build: ./contenedor_back_end
    restart: always
    container_name: eminus_crawler_back_end
    volumes:
      - ./contenedor_back_end/backend-crawler:/code/backend-crawler
      - ./contenedor_back_end/servicios_back_end:/code/servicios_back_end
    depends_on:
      - bd_back_end
    deploy:
      resources:
        limits:
          cpus: "3"
          memory: "3G"
        
      
  bd_front_end:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - ./contenedor_front_end/data:/var/lib/mysql

  nginx_front_end:
    image: nginx
    restart: always
    volumes:
      - ./contenedor_front_end/config/nginx/conf.d:/etc/nginx/conf.d
      - ./contenedor_front_end/front_end/static:/static
    depends_on:
      - front_end
    ports:
      - 8000:80

  bd_back_end:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_SERVICIOS_PASSWORD}
      MYSQL_DATABASE: ${DB_SERVICIOS_NAME}
    volumes:
      - ./contenedor_back_end/data:/var/lib/mysql

  nginx_back_end:
    image: nginx
    restart: always
    volumes:
      - ./contenedor_back_end/config/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - back_end
    ports:
      - 8001:80
